cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/mnt/hgfs/High-Precision-Congestion-Control-master/simulation/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/mnt/hgfs/High-Precision-Congestion-Control-master/simulation/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 140557748935376: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-O0\', \'-ggdb\', \'-g3\', \'-std=gnu++11\', \'-fno-strict-aliasing\', \'-fwrapv\', \'-fstack-protector\', \'-fno-strict-aliasing\', \'-I/usr/include/python2.7\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DNDEBUG\', \'-D_FORTIFY_SOURCE=2\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
